### ISSUE TITLE
development environment issues "window is not defined"

### ISSUE THREAD

**Issue by marekzan** [dnass/svelte-canvas#10]
I initialized a completely new project using

`npm init svelte@next project`

and in the `routes/index.svelte` I did paste the example code from the readme.

After running `npm run dev` I encountered the error 'window is not defined'.
After googling a bit, it seems to be an SSR issue.

While looking at the svelte-canvas code I realized that it is using onMount in Canvas.svelte, which should be used when calling browser internal API.

But in the lines 46 and 73 there is a call to the window object which is probably the cause of my problem.

I had to use

```
{#if browser}
  <Canvas width={640} height={640}>
    <Layer {render} />
  </Canvas>  
{:else}
  <p>This default content will be shown on pre-render and SSR</p>
{/if}
```

u/anniedillard on reddit pointed me to the solution: https://www.reddit.com/r/sveltejs/comments/qlz4q6/how_to_dev_with_sveltecanvas/

**Comment by dnass** [comment]
@marekzan Thanks for flagging this — it's been fixed in 0.7.1.
