### ISSUE TITLE
drawImage doesn't (always) draw

### ISSUE THREAD

**Issue by joakim** [dnass/svelte-canvas#11]
https://svelte.dev/repl/9876cca0f1c2410b8920fec3fbc81375?version=3.44.2

On first load, the chess pieces are not shown. Usually. Sometimes a few might be.

Make an edit to the source code to trigger live reload, and all the pieces will be drawn.

This happens even if I preload the images. Any ideas what could be going on here?

**Comment by dnass** [comment]
Image loading in JS is asynchronous, so even though you start preloading the images before the first render, there's no guarantee they'll be finished loading by the time they're needed. One solution is to trigger a re-render in the `Piece` component when the image's [`onload` handler](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onload) fires: https://svelte.dev/repl/333d0e40d09c4e55bc7f3ee8dd0d3d68?version=3.44.2

**Comment by joakim** [comment]
That did the trick 👍 

Thanks a lot for helping out, and so quickly!
