### ISSUE TITLE
Documentation for using methods (getCanvas, getContext, redraw)

### ISSUE THREAD

**Issue by abhsarma** [dnass/svelte-canvas#13]
I am not super familiar with JS, so it would be helpful to have examples on how to use the methods described in the documentation.

I am not sure if there's an object (say x) on which these methods need to be called (`x.getCanvas()`) or if there's an argument that needs to be passed to these methods (`getCanvas(x)`)

Some examples would make this much more accessible. Thanks!

**Comment by dnass** [comment]
You're totally right, those methods need better documentation and I'll add some soon. In the meantime, here's an [example](https://svelte.dev/repl/789e3e064cb34f2db8f0d5f7ecfe7f36?version=3.49.0) showing how to use them. There are two options: you can use Svelte's [`bind:this`](https://svelte.dev/docs#template-syntax-component-directives-bind-this) to get the component instance and call the methods on it, like `x.getCanvas()`, or you can use [property binding](https://svelte.dev/docs#template-syntax-component-directives-bind-property) to access the individual methods directly, like `getCanvas()`. None of the methods take any arguments.

Happy to help if you have any other questions about the library!
