### ISSUE TITLE
Is there a way to control the timer?

### ISSUE THREAD

**Issue by tansanDOTeth** [dnass/svelte-canvas#16]
I'm looking to try Svelte with canvas and I found this library. I noticed you can immediately subscribe to `t`, but wasn't sure if you can manually start/stop the timer. 

Also, are there plans to use `performance` over `Date`? d3 timer uses this here: https://github.com/d3/d3-timer/blob/main/src/timer.js#L10

Edit: Also, nice to see that you added the support for pixel ratio! I spent hours trying to figure out why my canvas was so blurry. 

https://github.com/dnass/svelte-canvas/blob/3497d9184192cd361bc12d2ed03179fd32ff115f/src/lib/components/Canvas.svelte#L149-L153

**Comment by dnass** [comment]
Hey, I currently don't have plans to make either of those changes. The timer uses a `requestAnimationFrame` loop which is limited by the screen refresh rate, so I'm not sure how useful sub-millisecond timing would be there. `t` doesn't have start/stop methods — the main use is just to drive the reactive render loop, and you'd typically handle starting and stopping the animation in your layer's render function. But you could definitely try creating a [custom Svelte store](https://svelte.dev/docs#component-format-script-4-prefix-stores-with-$-to-access-their-values-store-contract) that meets your requirements.

**Comment by tansanDOTeth** [comment]
> Hey, I currently don't have plans to make either of those changes. The timer uses a `requestAnimationFrame` loop which is limited by the screen refresh rate, so I'm not sure how useful sub-millisecond timing would be there. `t` doesn't have start/stop methods — the main use is just to drive the reactive render loop, and you'd typically handle starting and stopping the animation in your layer's render function. But you could definitely try creating a [custom Svelte store](https://svelte.dev/docs#component-format-script-4-prefix-stores-with-$-to-access-their-values-store-contract) that meets your requirements.

Thank you for the reply! Great library by the way! It looks really nice.

**Comment by dnass** [comment]
Thanks! If you have any other feedback I'm happy to hear it.
