### ISSUE TITLE
Does the `render` function always re-run?

### ISSUE THREAD

**Issue by tansanDOTeth** [dnass/svelte-canvas#17]
I noticed my animation  stutters unless I reference `$t` in the render function. I am guessing the render function is cached by Svelte and subscribing to `t` helps re-assign a new render function. Do you happen to know why this is happening? do I need to use the redraw function? if so, could you share an example of how I can use that function?

**Comment by dnass** [comment]
If `render` is declared reactively, it will automatically redraw anytime a value that it depends on changes. You don't need to use `$t` to achieve a smooth animation, but you should use a `requestAnimationFrame` loop to change the values that you're animating. Here's a simple [example](https://svelte.dev/repl/014a09e3713f4055b65c2006611c5822?version=3.55.1).

**Comment by tansanDOTeth** [comment]
> you should use a `requestAnimationFrame` loop to change the values that you're animating. Here's a simple [example](https://svelte.dev/repl/014a09e3713f4055b65c2006611c5822?version=3.55.1).

Wait, I was under the impression that this library supplies the loop with `requestAnimationFrame` for you behind the scenes and you just had to supply the render function. Did I misunderstand?

**Comment by tansanDOTeth** [comment]
> If `render` is declared reactively, it will automatically redraw anytime a value that it depends on changes.

That's what I understood, but it wasn't drawing unless I specifically references `$t`. I actually have the app working with at timer using React, but was testing it in Svelte with this library to see if I could gain additional performance speeds. 

So this is what my function looks something like and if I comment out `$t` then it's very choppy and skips animation. However, with `$t`, it works as I would expect. Now that I am writing this, I am wondering if I need to use a tick here? 

```
$: render = ({ context, width, height }) => {
  $t; 
  for (let point of points) {
    draw(context, $store, point);
  }
};
```

**Comment by dnass** [comment]
Which of the variables inside `render` is changing, and how are you changing it? In order for Svelte's reactivity to work, you have to [change variables through assignment](https://svelte.dev/tutorial/updating-arrays-and-objects).

**Comment by tansanDOTeth** [comment]
> Which of the variables inside `render` is changing, and how are you changing it? In order for Svelte's reactivity to work, you have to [change variables through assignment](https://svelte.dev/tutorial/updating-arrays-and-objects).
> 
> EDIT: To answer your first question, the library runs a rAF loop that checks if any of the render functions has changed and schedules a render if it has. If nothing has changed, there's no render. If you want to redraw on every frame, `render` needs to change every frame — including `$t` inside the function is a simple way to do that.

`points` was changing. I couldn't quite figure out what the issue was, but thank you for giving me insight into your library!
