### ISSUE TITLE
Q: Is it possible to draw div elements inside canvas?

### ISSUE THREAD

**Issue by jerrygreen** [dnass/svelte-canvas#18]
Aside div or other native tags, I wanna draw other svelte components inside canvas. I have my reason why I would like to do that: rare use-case, but I need that. Is that possible with svelte-canvas? Any idea how can be that possible?

**Comment by LeoDog896** [comment]
Theres no official API that supports it, but what I've done with [older projects](https://github.com/LeoDog896/conspirasea) before I found about svelte-canvas is use a fixed element position and use [`top`](https://developer.mozilla.org/en-US/docs/Web/CSS/top) and [`left`](https://developer.mozilla.org/en-US/docs/Web/CSS/left) CSS properties to position the div elements manually.

(P.S. @dnass you should enable discussions for this repository. It seems that Q/A issues are getting more common.)

**Comment by dnass** [comment]
Yeah, elements added as children of a `canvas` won't even appear on the page. The best way to approach this is to absolutely position a div to cover the same area as the canvas as an overlay, and then add elements or svelte components inside of that. Here's a related [example](https://svelte.dev/repl/0df2613d2bff4ac89735edc628955937?version=3.55.1) — it uses SVG instead of HTML but the approach is the same.

**Comment by jerrygreen** [comment]
Okay, I think what I said isn’t enough: «I have my reason why I would like to do that».

Now then let me explain: while I still want to use declarative way to render interfaces with HTML and Svelte I want to achieve some retro pixilazation effect by having reliable pixel grid. This isn’t normally achievable in web. On a quick thought, you might think: just render html as normal but at small size then apply some zoom etc property. This doesn’t work. None css properties work, believe me I tried them all. The problem is that browser will re-apply aliasing, no matter which tag or css properties you use. No matter… Except canvas. While drawing on canvas, browsers take attention only to its width & height property. Therefore, after zooming canvas, the picture will not be aliased, having exact same pixilazation effect I need. But this requires drawing everything on canvas. I wanted to skip this long explanation by saying: «I have my reasons», but you seem still to persuade me I don’t need that 😅

Your example in readme looked promising to me:

```jsx
<Canvas width={640} height={640}>
  <Layer {render} />
</Canvas>
```

Because I thought, and hoped, this also possible:

```jsx
<Canvas width={640} height={640}>
  <p>Something</p>
  <button>Some button</button>
  <div>e.t.c.</div>
</Canvas>
```

P.S. From your answers, I see you can’t help as your library doesn’t support that, now I get it. I did explain just for having an understanding. Sorry for your taken time.

**Comment by LeoDog896** [comment]
If it helps, there's a relevant SO thread: https://stackoverflow.com/questions/12652769/rendering-html-elements-to-canvas

**Comment by dnass** [comment]
You might also be able to achieve the pixilation effect with an SVG filter like this https://codepen.io/tigt/pen/aZYqrg
