### ISSUE TITLE
Layer events compatibility with resized layers

### ISSUE THREAD

**Issue by martinbaste** [dnass/svelte-canvas#21]
The layer event functionality that was recently added is awesome! 

I'm trying to get it to work with a layer that has been resized, but the mouse events seem to ignore the resizing. 

I've tried using `context.scale`, `context.setTransform` (in Layer `setup` and `render`) and resizing with css, but the mouse events seem to stick to the original size elements.

Do you have any suggestions on how to handle this? I want to resize the layers because I have the elements to be drawn in a specific size but I want to resize the canvas scale based on the screen size etc.

**Comment by martinbaste** [comment]
Of course, not long after posting the question I find a solution. In case its useful for the next one.

Set Canvas `width` and `height` to the full/original size you have your layers in. Then set Canvas `style` to `transform: scale(${scale}); transform-origin: left top;` where `${scale}` is the size of how big the canvas will show divided by the full/original size.

**Comment by dnass** [comment]
Hey, glad you found a working solution. You're right that `context.setTransform` and `context.scale` commands break layer events, and I'll look into a fix for that — thanks for flagging.

For the case you're describing, another route would be to adjust the `width` and `height` props on the `Canvas` component to take up the space you need, and then update your `render` functions to draw the layers relative to the size of the parent canvas. The advantage of that over your current approach is that you'll get consistent pixel density — sizing up the canvas with `transform: scale` might not look great on retina displays. But no need to mess with it if it's getting the job done!

**Comment by martinbaste** [comment]
What is drawn is generated pixel by pixel based on a size of 2000x2000, so I would need an algorithm to scale it down before drawing it (or using `context.setTransform` or `context.scale` after). Since I'm always scaling down, the `transform: scale` should be fine. 

Getting `context.setTransform` or `context.scale` to work would be great, but our current solution works for now. Thanks for making and releasing svelte-canvas!

**Comment by dnass** [comment]
Ah, makes sense. I'll drop a note in this thread when I have a fix for `setTransform`.

**Comment by dnass** [comment]
Layer events now work with `context.scale` and `context.setTransform` in 0.9.3 — if you have a chance to try it out, let me know how it goes.
