### ISSUE TITLE
Canvas doesn't cover full height

### ISSUE THREAD

**Issue by fromtheeast710** [dnass/svelte-canvas#29]
I'm learning `svelte-canvas` and unable to fit the height of the canvas to the window. The height would stay 640px and if I use append class `h-full`, the window would overflow. The width works as expected which confuses me.

Here's my setup:

```html
<script>
    import { Canvas } from 'svelte-canvas';
    let width, height;
</script>

<div bind:clientWidth={width} bind:clientHeight={height}>
  <Canvas
    {width}
    {height}
    style="cursor: pointer"
  >
  </Canvas>
</div>

<style>
  div {
    width: 100%;
    height: 100%;
    background-color: white;
  }
</style>
```

**Comment by LeoDog896** [comment]
It seems to work as expected in a [Svelte REPL](https://svelte.dev/repl/508de9e56d6f4536b5b310e58d3f4fbf?version=4.2.1).

**Comment by dnass** [comment]
[Percentage height in CSS](https://stackoverflow.com/questions/31728022/why-is-percentage-height-not-working-on-my-div/31728799#31728799) only works if all of an element's parents (including `html` and `body`) have an explicit height as well. The other option is to use `height: 100vh`, which will work on its own.
