### ISSUE TITLE
TypeScript usage

### ISSUE THREAD

**Issue by BCsabaEngine** [dnass/svelte-canvas#34]
Hello!

I would like to use this lib to create layout for my modeltrain hobby. With svelteKit I need to use TypeScript. I could use TS in this format: 
```
$: setup = ({ width, height }: { width: number; height: number })...

$: render = ({ context }: { context: CanvasRenderingContext2D })...
```
but I cannot find proper type for ```on:mousemove={onMove}``` in https://dnass.github.io/svelte-canvas/examples/layer-events.

Can you help me?

**Comment by BCsabaEngine** [comment]
ps: Cannot find event types in https://github.com/dnass/svelte-canvas/issues/9

**Comment by dnass** [comment]
You can use the `CanvasLayerEvent` type – there's an example [here](https://dnass.github.io/svelte-canvas/components/layer#canvaslayerevent).

**Comment by hyuckkim** [comment]
Can I write to this? I got error on that example.

```
Argument of type '(e: CanvasLayerEvent) => void' is not assignable to parameter of type '(e: LayerEventDetail) => void'.
  Types of parameters 'e' and 'e' are incompatible.
    Type 'LayerEventDetail' is missing the following properties from type 'CustomEvent<LayerEventDetail>': detail, initCustomEvent, bubbles, cancelBubble, and 20 more.ts(2345)
```

on:
- node v20.11.1
- pnpm 8.15.4
- svelte 4.2.7
- typescript 5.0.0
- vite 5.0.3
- svelte-canvas 1.1.2
