### ISSUE TITLE
Question: keyboard events

### ISSUE THREAD

**Issue by Thebigbignooby** [dnass/svelte-canvas#36]
I just found this library, it looks cool and easy to use, well done!

As a fun project, I've set myself the challenge of cloning Google Sheets using Svelte.
I realised that the enter sheet is actually built with canvas, hence how I found svelte-canvas.

Would svelte-canvas cut the mustard in my endeavour or would you recommend something like Konva?

I see that you handle mouse and touch events, but what about keyboard events?
When editing a formula, it is possible in google sheets to navigate the sheet using the keyboard arrows.
Submitting cell content with "Enter" or "Tab"
toggle a cell edit on "Enter"
etc...

I new to canvas so not sure what the simplest and/or technically possible solution is.
By the looks of it I might have to handle these outside the canvas context but it's still quite unclear to me at this time.

**Comment by dnass** [comment]
`svelte-canvas` doesn't support keyboard events on the `Canvas` or `Layer` components, though [neither does Konva](https://konvajs.org/docs/events/Keyboard_Events.html). I do think your best bet would be to handle it at the `document` level, and keep track of the cell values and other state in a parent component. Here's an example of what that could look like:

```
<script>
  // let's say the value of each cell is stored in a Map with keys [x, y]
  const cells = new Map()
  cells.set([0, 0], '')

  let active;
</script>

<Canvas>
  {#each cells as [[x, y], value]}
    <Cell {x} {y} {value} on:click={() => (active = [x, y])} />
  {/each}
</Canvas>

<svelte:document
  on:keydown={(e) => {
    // Enter increments active cell row by 1 
    if (e.key === 'Enter') active[0]++;

    // Tab increments active cell col by 1
    else if (e.key === 'Tab') active[1]++;

    // Otherwise, add the key to the cell's value
    else cells.set(active, cells.get(active) + e.key)
  }}
/>
```

Building a spreadsheet is probably pretty challenging and I can't promise this is the best direction, but hope it's helpful!
