### ISSUE TITLE
Thanks for a splendid library!

### ISSUE THREAD

**Issue by voxpelli** [dnass/svelte-canvas#38]
As an OSS maintainer myself I know its nice to get some positive feedback every once in a while, and I must say, this library made it so very simple to add a reactive canvas element into Svelte, so I thought I would send you a thanks and also let you know that I've used in production and that it so far works great 🙏 

![Image from iOS](https://github.com/dnass/svelte-canvas/assets/34457/fdefa91c-ece0-46af-95ce-d15cd24947b7)

My use case was to draw arrows between HTML elements in a graph layout generated by [`@dagrejs/dagre`](https://github.com/dagrejs/dagre) and with this one I could easily reactively sync hover states etc with the HTML elements without any excessive re-rendering 🎉

**Comment by dnass** [comment]
Well this made my day — really glad to hear the library is working well for you!
