### ISSUE TITLE
Cannot read property '$$' of undefined

### ISSUE THREAD

**Issue by thegamingninja** [dnass/svelte-canvas#4]
Problem
---
The `<Canvas>` element throws hundreds of `Uncaught TypeError` errors while hovering over it, the canvas works as intended, however it causes the browser to hang a lot when the debug console is open.

Full Error
---
```
node_modules/svelte/internal/index.mjs:691 Uncaught TypeError: Cannot read property '$$' of undefined
    at bubble (node_modules/svelte/internal/index.mjs:691)
    at HTMLCanvasElement.eval (node_modules/svelte-canvas/src/forwardEvents.js:24)
```

Possible Cause
---
I don't have enough experience with canvas and event forwarding to understand what might be going on, but the problem seems to be coming from this line
https://github.com/dnass/svelte-canvas/blob/cf1dd0efc18c3c2bcfd24330091ee01ada0b06d2/src/forwardEvents.js#L24

**Comment by dnass** [comment]
Thanks, can you share a code snippet that reproduces this issue?

**Comment by thegamingninja** [comment]
I just copied all the related code to a separate project to try and reproduce the issue, however, I'm unable to, though I find out it seems to be related to `component` in [this line](https://github.com/sveltejs/svelte/blob/dafbdc286eef3de2243088a9a826e6899e20465c/src/runtime/internal/lifecycle.ts#L65) being undefined in `svelte/internal`. So it might be an issue related to something in svelte itself.
