### ISSUE TITLE
Integrate with `canvas-size` to gracefully handle too large canvases

### ISSUE THREAD

**Issue by voxpelli** [dnass/svelte-canvas#40]
I've run into a couple of times that the canvas that I've set up is too large for the device that I'm using, eg. iphones being extra restrictive.

While I can test my width/height myself, the canvas that's set up by `svelte-canvas` can more easily ensure that its calculated with the correct device pixel ratio + ensure that the hit-canvas is not too big either.

Here's the library: https://jhildenbiddle.github.io/canvas-size/

One thing `svelte-canvas` could offer to do as well is to reduce the device pixel ratio until the canvas fits: If eg. area is 2x larger than possible, divide pixel ratio by 2 and render at a lower resolution.

**Comment by dnass** [comment]
This was a great suggestion. As of v1.1.1, setting `pixelRatio='auto'` on Canvas will automatically scale down the pixel ratio in increments of 0.1 until it finds a working value.
