### ISSUE TITLE
Allow touch scrolling while `layerEvents` are active

### ISSUE THREAD

**Issue by voxpelli** [dnass/svelte-canvas#41]
The same big canvas that I mentioned in #40 is, when it isn't too big, still too big to be seen in one full iPhone screen, but scrolling past it becomes a challenge as `layerEvents` are active and that seems to be preventing touch scrolling completely.

Any idea what could be done to help here?

**Comment by dnass** [comment]
Great point. The library has been calling `preventDefault` on all touch handlers, but I think it's reasonable to remove those calls and tell users to call `e.detail.originalEvent.preventDefault()` if they want to prevent scroll when interacting with a specific layer. Just resolved this in #43.
