### ISSUE TITLE
Events at the Layer level?

### ISSUE THREAD

**Issue by jarmitage** [dnass/svelte-canvas#5]
Thanks for this library!

Currently I am not sure how I would make changes to Layers based on events happening at the Canvas level, particularly if there might be a non-trivial number of Layers (and sub-Layers?). I can of course use `bind` but it feels strange to propagate events down the layers / components rather than up.

I was wondering if you have a solution for this already, or whether you have one in mind such as `$: render = ({ context, width, height, event }) => {}` etc

**Comment by dnass** [comment]
There's no "official" way to pass events to Layers, but [here's an approach](https://svelte.dev/repl/e070c32b6a5e4c25b5b295f3d67b87c4?version=3.40.3) that adds an `event` prop to the layer render function using a store and a wrapper component. You'd just need to add handlers on the Canvas for every type of event you want to listen to.

**Comment by jarmitage** [comment]
That makes sense, thanks for the example. 

Another limitation of this approach is the re-rendering of Layers when the event occurs outside of their bounds.

**Comment by dnass** [comment]
Yeah, the Canvas doesn't have any out-of-the-box way of knowing where a Layer's bounds are. There are [ways of doing it yourself](https://lavrton.com/hit-region-detection-for-html5-canvas-and-how-to-listen-to-click-events-on-canvas-shapes-815034d7e9f8/), though at some point you might be better off using Konva or Fabric.

**Comment by dnass** [comment]
Hey @jarmitage, it's been a while but wanted to give you a heads up that the latest version of svelte-canvas includes layer events. The library takes care of hit detection and forwarding DOM events from the canvas to the appropriate layer. There are some details in the [readme](https://github.com/dnass/svelte-canvas#event-handling) and [this example](https://github.com/dnass/svelte-canvas/tree/master/src/routes/layer-events). It's a bit of an experiment, so if you get around to trying it out, let me know how it goes.
