### ISSUE TITLE
Q: Image is not work with layer event. Is it a feature?

### ISSUE THREAD

**Issue by hyuckkim** [dnass/svelte-canvas#51]
I am using the library well.
so I drawn a transparent image then everything works right.

However I don't understand that why drawImage don't work with canvas event.
Is there a reason?

**Comment by dnass** [comment]
`drawImage` does work with layer events — here's a [simple example](https://svelte.dev/repl/4ce42740f1544dc89f7d15d66352350e?version=4.2.12). If you share your code that's not working, I can try to help you find the issue.
