### ISSUE TITLE
layer events on drawImage with nine parameter working wrong

### ISSUE THREAD

**Issue by hyuckkim** [dnass/svelte-canvas#52]
I made a sprite system on svelte-canvas.

Click position is generate without actually display position, instead that with source position.
I think it is a bug.

https://svelte.dev/repl/431f480a2ef545538a6d97cec8bc3e9d?version=4.2.14

**Comment by dnass** [comment]
You're right, the nine-argument version of `drawImage` wasn't being handled correctly. This is fixed in 1.1.2.
