### ISSUE TITLE
Add support for toggling alpha property of context

### ISSUE THREAD

**Issue by FluentCoding** [dnass/svelte-canvas#55]
It would be awesome if we could pass the alpha property on the Canvas component for optimizing rendering performance, see the official docs: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Optimizing_canvas?retiredLocale=de#turn_off_transparency

https://github.com/dnass/svelte-canvas/blob/5bc9be92ad9b4cbfe21a5d363427558dd328a670/src/lib/components/Canvas.svelte#L69

**Comment by LeoDog896** [comment]
This can be extended to [any one of the properties](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext#contextattributes).

**Comment by dnass** [comment]
Yeah, this is a great idea — I'm thinking `Canvas` should have a `contextOptions` prop that gets passed along to `canvas.getContext`. Will work on this soon.

**Comment by dnass** [comment]
Added this in version 1.2.0. You can do `<Canvas contextSettings={{ alpha: false }}>` to create a context with alpha disabled.
