### ISSUE TITLE
Tween Scatter Plot example please

### ISSUE THREAD

**Issue by SumNeuron** [dnass/svelte-canvas#7]
Please :)

**Comment by dnass** [comment]
How's this: https://svelte.dev/repl/d94a3d12a8dc4408a8389b2601fdea03?version=3.38.2

**Comment by SumNeuron** [comment]
No bad! But doesn’t use tween?

**Comment by dnass** [comment]
It uses [tweened stores](https://svelte.dev/docs#tweened) — are you talking about something else?
